language: node_js
node_js:
  - node
cache: npm

env:
  global:
    - NODE_ENV=test
    - GITHUB_REPO="devdbrandy/restful-ecommerce"

after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE restecommerce_test;' -U postgres
  - npm run migrate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

notifications:
  email: false
